;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-line-text
        cua--prefix-override-handler
        cua-paste
        hungry-delete-backward
        hungry-delete-forward
        org-self-insert-command
        org-set-tags-command
        org-shiftright
        ))

(setq mc/cmds-to-run-once
      '(
        handle-select-window
        scheme-compile-definition-and-go
        ))
