(deftheme moe-mage
  "Created 2019-12-14.")

(custom-theme-set-variables
 'moe-mage
 '(ansi-color-names-vector ["#333" "#ff5f87" "#3affa3" "#f6df92" "#b2baf6" "#c350ff" "#5af2ee" "#ccc"]))

(custom-theme-set-faces
 'moe-mage
 '(cursor ((((class color) (min-colors 89)) (:background "#acfb5a"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#222"))))
 '(linum ((((class color) (min-colors 89)) (:background "#222"))))
 '(line-number ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4e4e4e"))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:background "#d7ff5f" :foreground "#3a3a3a"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#222"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#3a3a3a"))))
 '(region ((((class color) (min-colors 89)) (:background "#34004A"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#222"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#f6df92" :background "#050505" :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#5af2ee" :background "#050505" :inverse-video t))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "red" :underline nil))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#FFE200" :background nil :slant italic :weight bold))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#c350ff" :background nil))))
 '(help-argument-name ((((class color) (min-colors 89)) (:foreground "#ff7bbb" :italic t))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#acfb5a" :weight bold))))
 '(mode-line ((t (:foreground "#eee" :background "#331133"))))
 '(mode-line-inactive ((t (:foreground "#643" :background "#110011" :weight light :box nil :inherit (mode-line)))))
 '(mode-line-buffer-id ((t (:foreground "#f6df92"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#4e4e4e"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#3aff83"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#f09fff"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#d020a7"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#ff5f87"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#f25a5a"))))
 '(completions-annotations ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(completions-common-part ((((class color) (min-colors 89)) (:foreground "#6c6c6c"))))
 '(completions-first-difference ((((class color) (min-colors 89)) (:weight bold :foreground "#ff8700"))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#f6df92"))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#ff5f87"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#aa2255"))))
 '(org-archived ((((class color) (min-colors 89)) (:slant italic))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#c6c6c6" :foreground "#4e4e4e" :box (:line-width 1 :style released-button)))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#b2baf6" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#f25a5a"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "#dcdff2"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:foreground "#f09fff"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(org-tag ((((class color) (min-colors 89)) (:foreground "#78537A"))))
 '(org-column ((((class color) (min-colors 89)) (:inherit default))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#c350ff" :weight bold :underline t))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#a86"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#a86"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:inherit default))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#050505" :background "#050505"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#3affa3" :underline t))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#888"))))
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff" :bold t))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "white"))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:foreground "#d18aff" :underline nil :bold nil))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#afd7ff" :background "#6c6c6c" :slant italic :weight bold))))
 '(org-agenda-column-dateline ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#4e4e4e" :underline t))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#77bb33"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#888"))))
 '(org-priority ((((class color) (min-colors 89)) (:foreground "#ef2929" :background nil))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#005f87"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#3a3a3a"))))
 '(org-quote ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#4e4e4e"))))
 '(org-mode-line-clock ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff" :bold t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#ef2929" :bold t))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(outline-6 ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(outline-7 ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(outline-8 ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#acfb5a" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(markdown-blockquote-face ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#4e4e4e" :italic t))))
 '(markdown-bold-face ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :bold t))))
 '(markdown-comment-face ((((class color) (min-colors 89)) (:foreground "#8a8a8a" :italic t))))
 '(markdown-header-delimiter-face ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(markdown-header-face ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-header-rule-face ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(markdown-header-face-5 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-header-face-6 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:foreground "#b2baf6" :underline t))))
 '(markdown-inline-code-face ((((class color) (min-colors 89)) (:foreground "white"))))
 '(markdown-italic-face ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :italic t :underline "#c6c6c6"))))
 '(markdown-list-face ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(markdown-math-face ((((class color) (min-colors 89)) (:foreground "#ff7bbb"))))
 '(markdown-missing-link-face ((((class color) (min-colors 89)) (:foreground "#ef2929" :bold t))))
 '(markdown-pre-face ((((class color) (min-colors 89)) (:foreground "white"))))
 '(markdown-reference-face ((((class color) (min-colors 89)) (:foreground "#ff8700" :italic t))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:inherit link))))
 '(company-echo ((((class color) (min-colors 89)) (:background nil :foreground "#c6c6c6"))))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#4e4e4e" :foreground "#ef2929"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#eee"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#eee" :underline t))))
 '(company-preview-search ((((class color) (min-colors 89)) (:foreground "black" :background "#f6df92"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#643"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#f6df92"))))
 '(company-template-field ((((class color) (min-colors 89)) (:background "#ffffaf" :foreground "#3a3a3a"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#1B0026" :foreground "#ccc"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#ef2929"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#eee"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:background "#d7ff5f" :foreground "#303030"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#c350ff" :foreground "black"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#3affa3" :underline t))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#d0bf8f"))))
 '(helm-buffer-directory ((t (:foreground "#c350ff"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "red" :background "#050505" :inverse-video t))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:background "#050505" :foreground "#f6df92" :bold t))))
 '(helm-ff-directory ((t (:foreground "#c350ff"))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#303030"))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#dd0000"))))
 '(helm-ff-prefix ((t (:foreground "#f6df92" :weight bold))))
 '(helm-grep-cmd-line ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff87" :bold t))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#d18aff"))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#fce94f" :bold t))))
 '(helm-header ((((class color) (min-colors 89)) (:inherit header-line))))
 '(helm-lisp-show-completion ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#d7ff5f"))))
 '(helm-match ((t (:foreground "#f6df92"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#333" :underline t))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#ccc" :foreground "#f6df92" :underline nil))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#050505" :foreground "#ff5f87" :underline t :weight bold))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:background "#333" :foreground "#c350ff" :bold t))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#303030" :background "#a1db00" :bold t))))
 '(dired-ignored ((((class color) (min-colors 89)) (:foreground "#a8a8a8"))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#dd0000" :bold t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#a40000" :bold t))))
 '(magit-bisect-bad ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf"))))
 '(magit-bisect-good ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff5f"))))
 '(magit-bisect-skip ((((class color) (min-colors 89)) (:foreground "#875f00" :background "#ffd787"))))
 '(magit-blame-date ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#4e4e4e"))))
 '(magit-blame-hash ((((class color) (min-colors 89)) (:foreground "#ff8700" :background "#4e4e4e"))))
 '(magit-blame-heading ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#4e4e4e"))))
 '(magit-blame-name ((((class color) (min-colors 89)) (:foreground "#afff00" :background "#4e4e4e"))))
 '(magit-blame-summary ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#4e4e4e"))))
 '(magit-branch-current ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#ff8700" :bold t :underline nil))))
 '(magit-branch-local ((((class color) (min-colors 89)) (:foreground "#3affa3"))))
 '(magit-branch-remote ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(magit-cherry-equivalent ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(magit-cherry-unmatched ((((class color) (min-colors 89)) (:foreground "#00ac8a"))))
 '(magit-diff-added ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(magit-diff-added-highlight ((((class color) (min-colors 89)) (:inherit magit-diff-added :weight bold))))
 '(magit-diff-base ((((class color) (min-colors 89)) (:foreground "#fce94f" :background nil))))
 '(magit-diff-base-highlight ((((class color) (min-colors 89)) (:foreground "#fce94f" :bold t :inherit (magit-section-highlight)))))
 '(magit-diff-conflict-heading ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#ff8700"))))
 '(magit-diff-context ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:inherit magit-diff-context :foreground "#eee"))))
 '(magit-diff-file-heading ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(magit-diff-file-heading-highlight ((((class color) (min-colors 89)) (:background "#005f87" :bold t))))
 '(magit-diff-file-heading-selection ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#8a8a8a" :bold t))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 89)) (:inherit magit-diff-hunk-heading :weight bold))))
 '(magit-diff-hunk-heading-selection ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#c6c6c6"))))
 '(magit-diff-lines-boundary ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#ff4b4b"))))
 '(magit-diff-lines-heading ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#ff4b4b"))))
 '(magit-diff-our ((((class color) (min-colors 89)) (:foreground "#ff1f8b"))))
 '(magit-diff-our-highlight ((((class color) (min-colors 89)) (:foreground "#ff1f8b" :background "#ffd7ff"))))
 '(magit-diff-removed ((((class color) (min-colors 89)) (:foreground "#f25a5a"))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 89)) (:inherit magit-diff-removed :weight bold))))
 '(magit-diff-their ((((class color) (min-colors 89)) (:foreground "#00ac8a"))))
 '(magit-diff-their-highlight ((((class color) (min-colors 89)) (:foreground "#005f5f" :background "#87ffff"))))
 '(magit-diff-whitespace-warning ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#a40000"))))
 '(magit-diffstat-added ((((class color) (min-colors 89)) (:foreground "#5faf00" :background "#d7ff5f" :bold t))))
 '(magit-diffstat-removed ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ff4b4b" :bold t))))
 '(magit-dimmed ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(magit-filename ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(magit-hash ((((class color) (min-colors 89)) (:foreground "white"))))
 '(magit-head ((((class color) (min-colors 89)) (:foreground "#d75f00" :background "#ffd7af"))))
 '(magit-header-line ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#a1db00" :background nil))))
 '(magit-log-date ((((class color) (min-colors 89)) (:foreground "#8a8a8a" :background nil))))
 '(magit-log-graph ((((class color) (min-colors 89)) (:foreground "#8a8a8a" :background nil))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf" :underline t))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#5faf00" :background "#d7ff87" :underline t))))
 '(magit-reflog-amend ((((class color) (min-colors 89)) (:foreground "#ff1f8b" :background "#ffd7ff"))))
 '(magit-reflog-checkout ((((class color) (min-colors 89)) (:foreground "#5faf00" :background "#d7ff87"))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 89)) (:foreground "#d75f00" :background "#ffd787"))))
 '(magit-reflog-commit ((((class color) (min-colors 89)) (:foreground "#875f00" :background "#ffff87"))))
 '(magit-reflog-merge ((((class color) (min-colors 89)) (:foreground "#6c0099" :background "#e6a8df"))))
 '(magit-reflog-other ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#4e4e4e"))))
 '(magit-reflog-rebase ((((class color) (min-colors 89)) (:foreground "#005f5f" :background "#87d7af"))))
 '(magit-reflog-remote ((((class color) (min-colors 89)) (:foreground "#005faf" :background "#afd7ff"))))
 '(magit-reflog-reset ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf"))))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#dcdff2"))))
 '(magit-section-heading-selection ((((class color) (min-colors 89)) (:background "#afd7ff"))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:foreground "#eee"))))
 '(magit-sequence-done ((((class color) (min-colors 89)) (:foreground "#5faf00"))))
 '(magit-sequence-drop ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(magit-sequence-head ((((class color) (min-colors 89)) (:foreground "#1f5bff"))))
 '(magit-sequence-onto ((((class color) (min-colors 89)) (:foreground "#af5fff"))))
 '(magit-sequence-part ((((class color) (min-colors 89)) (:foreground "#00ac8a"))))
 '(magit-sequence-pick ((((class color) (min-colors 89)) (:foreground "#ff4ea3"))))
 '(magit-sequence-stop ((((class color) (min-colors 89)) (:foreground "#a40000"))))
 '(magit-signature-bad ((((class color) (min-colors 89)) (:foreground "#dd0000"))))
 '(magit-signature-good ((((class color) (min-colors 89)) (:foreground "#5faf00"))))
 '(magit-signature-untrusted ((((class color) (min-colors 89)) (:foreground "#c4a000"))))
 '(magit-tag ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff"))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :background "#3a3a3a"))))
 '(magit-log-date ((((class color) (min-colors 89)) (:foreground "#c6c6c6" :background "#3a3a3a"))))
 '(magit-log-graph ((((class color) (min-colors 89)) (:foreground "#333"))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ffafaf" :underline t :bold t))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff87" :underline t :bold t))))
 '(magit-signature-bad ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(magit-signature-good ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(magit-signature-untrusted ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(magit-tag ((((class color) (min-colors 89)) (:foreground "#005f87" :background "#afd7ff"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:inherit message-header-to :foreground nil))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#c350ff" :background nil))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#5af2ee" :background nil :slant normal))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground nil :background nil :weight normal))))
 '(message-header-subject ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#f6df92"))))
 '(message-header-to ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#efc334"))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#a8a8a8"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#ff8700"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#78537A"))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "#6c6c6c"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#b2baf6" :background nil))))
 '(diff-function ((((class color) (min-colors 89)) (:foreground "#3a3a3a" :background "#c6c6c6"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#5af2ee" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(diff-index ((((class color) (min-colors 89)) (:foreground "#3a3a3a" :background "#b2b2b2" :bold t))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#5faf00" :bold t))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#c4a000" :bold t))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#a40000" :bold t))))
 '(diff-nonexistent ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#a40000" :bold t))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:inherit magit-diff-added-highlight :foreground "#dcdff2"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:inherit magit-diff-removed-highlight :foreground "#ffbbbb"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(smerge-refined-changed ((((class color) (min-colors 89)) (:background "#005f87" :foreground "#eeeeee"))))
 '(flyspell-duplicate ((((class color) (min-colors 89)) (:underline t foreground-color "#ffaf5f"))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:background "#ef2929" :foreground "#c6c6c6" :bold t))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:background "#87ffff" :foreground "#3a3a3a"))))
 '(avy-lead-face-0 ((((class color) (min-colors 89)) (:background "#e6a8df" :foreground "#3a3a3a"))))
 '(avy-lead-face-1 ((((class color) (min-colors 89)) (:background "#c6c6c6" :foreground "#3a3a3a"))))
 '(avy-lead-face-2 ((((class color) (min-colors 89)) (:background "#a1db00" :foreground "#3a3a3a"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(comint-highlight-prompt ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#6c6c6c" :bold t))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#b2baf6" :background nil :weight bold))))
 '(flymake-warning ((((class color) (min-colors 89)) (:underline "#efc334" :background "#050505"))))
 '(flymake-error ((((class color) (min-colors 89)) (:underline "red" :background "#050505"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:color "red")))))
 '(mmm-cleanup-submode-face ((((class color) (min-colors 89)) (:background "#ffd787"))))
 '(mmm-code-submode-face ((((class color) (min-colors 89)) (:background "#222"))))
 '(mmm-comment-submode-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mmm-declaration-submode-face ((((class color) (min-colors 89)) (:background "#87ffff"))))
 '(mmm-default-submode-face ((((class color) (min-colors 89)) (:background nil))))
 '(mmm-delimiter-face ((((class color) (min-colors 89)) (:background nil :foreground "#eeeeee"))))
 '(mmm-init-submode-face ((((class color) (min-colors 89)) (:background "#ffafd7"))))
 '(mmm-output-submode-face ((((class color) (min-colors 89)) (:background "#222"))))
 '(mmm-special-submode-face ((((class color) (min-colors 89)) (:background "#d7ff87"))))
 '(cider-deprecated-face ((((class color) (min-colors 89)) (:background "#5f0000"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#ff8700" :underline t))))
 '(js2-error ((((class color) (min-colors 89)) (:foreground "#dd0000" :underline t :bold t))))
 '(js2-warning ((((class color) (min-colors 89)) (:foreground nil :underline t :bold t))))
 '(erc-button ((((class color) (min-colors 89)) (:foreground "#5fafd7" :underline "#5fafd7" :bold nil))))
 '(erc-current-nick-face ((((class color) (min-colors 89)) (:foreground "#b2baf6" :weight bold))))
 '(erc-direct-msg-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(erc-error-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(erc-keyword-face ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:weight normal :foreground "#78537A"))))
 '(erc-nick-msg-face ((((class color) (min-colors 89)) (:weight normal :foreground "#f6df92"))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#333"))))
 '(erc-pal-face ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:foreground "#ff8700" :bold t :inherit highlight))))
 '(ivy-confirm-face ((((class color) (min-colors 89)) (:foreground "#008700" :background "#d7ff87" :bold t))))
 '(ivy-subdir ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(ivy-virtual ((((class color) (min-colors 89)) (:foreground "#ff1f8b"))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:background "#5fafd7" :foreground "#eeeeee"))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:bold t :background "#a1db00" :foreground "#eeeeee"))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:bold t :background "#ff4ea3" :foreground "#eeeeee"))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:bold t :background "#00d7af" :foreground "#eeeeee"))))
 '(swiper-match-face-1 ((((class color) (min-colors 89)) (:background "#5fafd7" :foreground "#eeeeee"))))
 '(swiper-match-face-2 ((((class color) (min-colors 89)) (:bold t :background "#a1db00" :foreground "#eeeeee"))))
 '(swiper-match-face-3 ((((class color) (min-colors 89)) (:bold t :background "#ff4ea3" :foreground "#eeeeee"))))
 '(swiper-match-face-4 ((((class color) (min-colors 89)) (:bold t :background "#00d7af" :foreground "#eeeeee"))))
 '(swiper-line-face ((((class color) (min-colors 89)) (:foreground "#ff8700" :bold t :inherit highlight))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "#afd7ff"))))
 '(widget-documentation ((((class color) (min-colors 89)) (:foreground "#afff00"))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#222" :box (:line-width 1 :color "#ccc")))))
 '(widget-inactive ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(widget-single-line-field ((((class color) (min-colors 89)) (:foreground "#d7ff5f" :background "#4e4e4e"))))
 '(table-cell ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#4e4e4e"))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "#a40000" :background "#ff4b4b" :bold t))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#3affa3"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "red"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(compilation-warning ((((class color) (min-colors 89)) (:foreground "#ff5d17"))))
 '(neo-banner-face ((((class color) (min-colors 89)) (:foreground "#5faf00" :background nil))))
 '(neo-header-face ((((class color) (min-colors 89)) (:foreground "#afff00" :background nil))))
 '(neo-root-dir-face ((((class color) (min-colors 89)) (:foreground "#ff7bbb"))))
 '(neo-button-face ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(neo-dir-link-face ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(neo-expand-btn-face ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background "#6c6c6c"))))
 '(neo-file-link-face ((((class color) (min-colors 89)) (:foreground "#c6c6c6"))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "#ff4ea3" :bold t))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#5fafd7" :background nil :bold t))))
 '(info-index-match ((((class color) (min-colors 89)) (:background "#005f87"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:foreground "#eeeeee" :bold t :underline t))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#ef2929"))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#a40000"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:foreground "#5fafd7" :bold t))))
 '(info-title-2 ((((class color) (min-colors 89)) (:foreground "#a1db00" :bold t))))
 '(info-title-3 ((((class color) (min-colors 89)) (:foreground "#ff8700" :bold t))))
 '(info-title-4 ((((class color) (min-colors 89)) (:foreground "#ff4ea3" :bold t))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "#5fafd7" :underline t))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:foreground "#d18aff" :underline t))))
 '(haskell-interactive-face-compile-error ((((class color) (min-colors 89)) (:foreground "#ff4b4b" :background nil :bold t))))
 '(haskell-interactive-face-compile-warning ((((class color) (min-colors 89)) (:foreground "#ff8700" :background nil :bold t))))
 '(haskell-interactive-face-garbage ((((class color) (min-colors 89)) (:foreground "#8a8a8a"))))
 '(haskell-interactive-face-prompt ((((class color) (min-colors 89)) (:foreground "#d7ff00" :background "#6c6c6c" :bold t))))
 '(haskell-interactive-face-result ((((class color) (min-colors 89)) (:foreground "#5fafd7"))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#a8a8a8" :background "#4e4e4e"))))
 '(tty-menu-disabled-face ((((class color) (min-colors 89)) (:foreground "#6c6c6c" :background "#4e4e4e"))))
 '(tty-menu-enabled-face ((((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#4e4e4e" :bold t))))
 '(tty-menu-selected-face ((((class color) (min-colors 89)) (:background "#005f87"))))
 '(web-mode-comment-face ((((class color) (min-colors 89)) (:foreground "#6c6c6c"))))
 '(web-mode-current-element-highlight-face ((((class color) (min-colors 89)) (:background "#4e4e4e"))))
 '(web-mode-current-column-highlight-face ((((class color) (min-colors 89)) (:background "#4e4e4e"))))
 '(web-mode-symbol-face ((((class color) (min-colors 89)) (:foreground "#ffd700"))))
 '(web-mode-type-face ((((class color) (min-colors 89)) (:foreground "#00d7af"))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#afd7ff" :foreground "#005f87" :box (:line-width 1 :style released-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#d7d7ff" :foreground "#4e4e4e" :box (:line-width 1 :style released-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:foreground "#4e4e4e" :background "#c6c6c6" :box (:line-width 1 :style pressed-button)))))
 '(default ((t (:background "#000000" :foreground "#ccc" :family "Hack"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(tooltip ((t (:foreground "#f8f8f2" :background "#44475a"))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#050505" :inherit font-lock-warning-face :inverse-video t))))
 '(match ((((class color) (min-colors 89)) (:foreground "#b2baf6" :background "#050505" :inverse-video t))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:background "#333333"))))
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(border ((((class color) (min-colors 89)) (:background "#222"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#050505" :inherit font-lock-warning-face :inverse-video t))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:foreground "#b2baf6" :background "#5555dd"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:foreground "#ff5f87" :background "#aa2255"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:foreground "#acfb5a" :background "#77bb33"))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:color "#efc334")))))
 '(helm-M-x-key ((((class color) (min-colors 89)) (:foreground "#ff5f87" :underline t))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "red"))))
 '(helm-ff-symlink ((t (:foreground "#f6df92"))))
 '(markdown-code-face ((((class color) (min-colors 89)) (:foreground "white"))))
 '(mm/master-face ((((class color) (min-colors 89)) (:inherit region :foreground nil :background nil))))
 '(mm/mirror-face ((((class color) (min-colors 89)) (:inherit region :foreground nil :background nil))))
 '(org-target ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(page-break-lines ((((class color) (min-colors 89)) (:foreground "#333"))))
 '(slime-repl-input-face ((((class color) (min-colors 89)) (:weight normal :underline nil))))
 '(slime-repl-prompt-face ((((class color) (min-colors 89)) (:underline nil :weight bold :foreground "#c350ff"))))
 '(slime-repl-result-face ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(slime-repl-output-face ((((class color) (min-colors 89)) (:foreground "#b2baf6" :background "#050505"))))
 '(web-mode-html-tag-face ((t (:foreground "#eee" :underline t))))
 '(web-mode-html-attr-name-face ((((class color) (min-colors 89)) (:inherit font-lock-doc-face))))
 '(web-mode-doctype-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face))))
 '(which-key-command-description-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(which-key-note-face ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(which-key-key-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face)))))

(provide-theme 'moe-mage)
