(deftheme rmage
  "Created 2019-12-04.")

(custom-theme-set-variables
 'rmage
 '(ansi-color-names-vector ["#333" "#ff5f87" "#3affa3" "#f6df92" "#b2baf6" "#c350ff" "#5af2ee" "#ccc"]))

(custom-theme-set-faces
 'rmage
 '(default ((t (:background "#000000" :foreground "#ccc" :family "Hack"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#acfb5a"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#222"))))
 '(region ((((class color) (min-colors 89)) (:background "#34004A"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#222"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "red" :underline nil))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#3aff83"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#f09fff"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#d020a7"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#ff5f87"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#f25a5a"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((((class color) (min-colors 89)) (:foreground "#3affa3" :underline t))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#d0bf8f"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#222"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#c350ff" :background nil))))
 '(tooltip ((t (:foreground "#f8f8f2" :background "#44475a"))))
 '(mode-line ((t (:foreground "#eee" :background "#331133"))))
 '(mode-line-buffer-id ((t (:foreground "#f6df92"))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#643" :background "#110011" :weight light :box nil :inherit (mode-line)))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#f6df92" :background "#050505" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#050505" :inherit font-lock-warning-face :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#5af2ee" :background "#050505" :inverse-video t))))
 '(match ((((class color) (min-colors 89)) (:foreground "#b2baf6" :background "#050505" :inverse-video t))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:background "#333333"))))
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#b2baf6" :background nil :weight bold))))
 '(border ((((class color) (min-colors 89)) (:background "#222"))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#222" :box (:line-width 1 :color "#ccc")))))
 '(success ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#FFE200" :background nil :slant italic :weight bold))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#050505" :inherit font-lock-warning-face :inverse-video t))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#eee"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#eee" :underline t))))
 '(company-preview-search ((((class color) (min-colors 89)) (:foreground "black" :background "#f6df92"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#1B0026" :foreground "#ccc"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#eee"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#c350ff" :foreground "black"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#643"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#f6df92"))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "red"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#3affa3"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#78537A"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#5af2ee" :background nil))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#b2baf6" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:inherit magit-diff-removed-highlight :foreground "#ffbbbb"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:inherit magit-diff-added-highlight :foreground "#dcdff2"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:foreground "#b2baf6" :background "#5555dd"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:foreground "#ff5f87" :background "#aa2255"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:foreground "#acfb5a" :background "#77bb33"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#acfb5a" :weight bold))))
 '(erc-direct-msg-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(erc-error-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(erc-current-nick-face ((((class color) (min-colors 89)) (:foreground "#b2baf6" :weight bold))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:weight normal :foreground "#78537A"))))
 '(erc-nick-msg-face ((((class color) (min-colors 89)) (:weight normal :foreground "#f6df92"))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#333"))))
 '(erc-pal-face ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(erc-keyword-face ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:color "red")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:color "#efc334")))))
 '(flymake-warning ((((class color) (min-colors 89)) (:underline "#efc334" :background "#050505"))))
 '(flymake-error ((((class color) (min-colors 89)) (:underline "red" :background "#050505"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:foreground "#eee" :weight normal))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#ccc" :weight normal))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#5af2ee" :weight normal))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "#efc334" :weight normal))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:foreground "#888" :weight normal))))
 '(gnus-summary-low-read ((((class color) (min-colors 89)) (:foreground "#333" :weight normal))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:foreground "#333" :weight normal))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:foreground "#f6df92" :weight normal))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "#acfb5a" :weight normal))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:foreground "#acfb5a" :weight normal))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "#efc334" :weight normal))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:foreground "red" :background nil :weight normal))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#333"))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:foreground "#333"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-3))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-1 :foreground "#888"))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-2 :foreground "#888"))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-3 :foreground "#888"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-5))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-6))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-7))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-8))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-1 :foreground "#888"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-2 :foreground "#888"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-3 :foreground "#888"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-4 :foreground "#888"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-5 :foreground "#888"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-6 :foreground "#888"))))
 '(helm-M-x-key ((((class color) (min-colors 89)) (:foreground "#ff5f87" :underline t))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "red" :background "#050505" :inverse-video t))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:background "#050505" :foreground "#f6df92" :bold t))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:background "#333" :foreground "#c350ff" :bold t))))
 '(helm-header ((((class color) (min-colors 89)) (:inherit header-line))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#333" :underline t))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#ccc" :foreground "#f6df92" :underline nil))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "red"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#050505" :foreground "#ff5f87" :underline t :weight bold))))
 '(helm-ff-directory ((t (:foreground "#c350ff"))))
 '(helm-ff-symlink ((t (:foreground "#f6df92"))))
 '(helm-buffer-directory ((t (:foreground "#c350ff"))))
 '(helm-match ((t (:foreground "#f6df92"))))
 '(helm-ff-prefix ((t (:foreground "#f6df92" :weight bold))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "red" :background "#050505"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#333"))))
 '(linum ((((class color) (min-colors 89)) (:background "#222"))))
 '(magit-log-graph ((((class color) (min-colors 89)) (:foreground "#333"))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:foreground "#eee"))))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#dcdff2"))))
 '(magit-branch-local ((((class color) (min-colors 89)) (:foreground "#3affa3"))))
 '(magit-branch-remote ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(magit-hash ((((class color) (min-colors 89)) (:foreground "white"))))
 '(magit-diff-file-heading ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 89)) (:inherit magit-diff-hunk-heading :weight bold))))
 '(magit-diff-context ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:inherit magit-diff-context :foreground "#eee"))))
 '(magit-diff-added ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(magit-diff-added-highlight ((((class color) (min-colors 89)) (:inherit magit-diff-added :weight bold))))
 '(magit-diff-removed ((((class color) (min-colors 89)) (:foreground "#f25a5a"))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 89)) (:inherit magit-diff-removed :weight bold))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:inherit link))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:foreground "#b2baf6" :underline t))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(markdown-header-delimiter-face ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(markdown-pre-face ((((class color) (min-colors 89)) (:foreground "white"))))
 '(markdown-code-face ((((class color) (min-colors 89)) (:foreground "white"))))
 '(markdown-inline-code-face ((((class color) (min-colors 89)) (:foreground "white"))))
 '(markdown-list-face ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(mm/master-face ((((class color) (min-colors 89)) (:inherit region :foreground nil :background nil))))
 '(mm/mirror-face ((((class color) (min-colors 89)) (:inherit region :foreground nil :background nil))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground nil :background nil :weight normal))))
 '(message-header-subject ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#f6df92"))))
 '(message-header-to ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#efc334"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:inherit message-header-to :foreground nil))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#c350ff" :background nil))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#5af2ee" :background nil :slant normal))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(mmm-code-submode-face ((((class color) (min-colors 89)) (:background "#222"))))
 '(mmm-comment-submode-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mmm-output-submode-face ((((class color) (min-colors 89)) (:background "#222"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "white"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#77bb33"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#888"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(org-column ((((class color) (min-colors 89)) (:inherit default))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#c350ff" :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#b2baf6" :underline t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#ff5f87"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#aa2255"))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#f6df92"))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#888"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#050505" :background "#050505"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "#dcdff2"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:foreground "#f09fff"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#3affa3" :underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#a86"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#efc334"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#a86"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#c350ff"))))
 '(org-tag ((((class color) (min-colors 89)) (:foreground "#78537A"))))
 '(org-target ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:inherit default))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#f25a5a"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(page-break-lines ((((class color) (min-colors 89)) (:foreground "#333"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#b2baf6"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#5af2ee"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-string-face :weight normal))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-preprocessor-face))))
 '(slime-repl-input-face ((((class color) (min-colors 89)) (:weight normal :underline nil))))
 '(slime-repl-prompt-face ((((class color) (min-colors 89)) (:underline nil :weight bold :foreground "#c350ff"))))
 '(slime-repl-result-face ((((class color) (min-colors 89)) (:foreground "#acfb5a"))))
 '(slime-repl-output-face ((((class color) (min-colors 89)) (:foreground "#b2baf6" :background "#050505"))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#acfb5a" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(web-mode-html-tag-face ((t (:foreground "#eee" :underline t))))
 '(web-mode-html-attr-name-face ((((class color) (min-colors 89)) (:inherit font-lock-doc-face))))
 '(web-mode-doctype-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face))))
 '(which-key-command-description-face ((((class color) (min-colors 89)) (:foreground "#f6df92"))))
 '(which-key-note-face ((((class color) (min-colors 89)) (:foreground "#ccc"))))
 '(which-key-key-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face)))))

(provide-theme 'rmage)
